### ISSUE TITLE
List of all TODO's

### ISSUE THREAD

**Issue by khalibartan** [pgmpy/pgmpy#548]
Here is al list of all TODO comments in pgmpy. I thought raising an issue regarding it can help us remove some. Removed TODO from CPD (since that particular section of code was commented out)
- [ ] independencies/Independencies.py:        # TODO: write reduce function.
- [ ] independencies/Independencies.py:        # TODO: Write this whole function
- [ ] inference/ExactInference.py:        # TODO: Modify it to find the optimal elimination order
- [X] models/BayesianModel.py:        # TODO: refer to IMap class for explanation why this is not implemented.
- [ ] models/DynamicBayesianNetwork.py:        # TODO: fix bugs in this
- [ ] models/MarkovModel.py:            # TODO : Convert factor into CPDs
- [ ] models/NoisyOrModel.py:        # TODO: Accept values of each state so that it could be
- [ ] readwrite/ProbModelXML.py:        # TODO: add policies, InferenceOptions, Evidence
- [ ] readwrite/ProbModelXML.py:        # TODO: add parsing of language and comments and additional properties
- [ ] readwrite/ProbModelXML.py:        # TODO: Add feature for accepting additional properties of states.
- [ ] readwrite/ProbModelXML.py:    # TODO: add methods to parse policies, inferenceoption, evidence etc.
- [ ] readwrite/ProbModelXML.py:    # TODO: add reading formatVersion
- [ ] readwrite/ProbModelXML.py:        # TODO: Do some checks with variable type and roles. Right now I don't know when they are to be used.
- [ ] readwrite/ProbModelXML.py:        # TODO: check for the case of undirected graphs if we need to add to both elements of the dic for a single edge.
- [ ] readwrite/XMLBeliefNetwork.py:                # TODO: Get Index value.

PS : Haven't manually checked all of them , used  `git grep` . 
Ping @ankurankan

**Comment by khalibartan** [comment]
@ankurankan Which TODO's we can work on right now ?

**Comment by ankurankan** [comment]
@khalibartan None of these are high priority for now. So, can start anywhere.

**Comment by khalibartan** [comment]
@anaviltripathi @yashu-seth

**Comment by pdoongarwal** [comment]
@ankurankan Which of these might be easy to work on? I'll like to work on them.

**Comment by nishnik** [comment]
@khalibartan @ankurankan Can you give me an example on what we have to extract from `policies`, `InferenceOptions` and `Evidence`. I would like to work on:
`readwrite/ProbModelXML.py: # TODO: add policies, InferenceOptions, Evidence`

**Comment by khalibartan** [comment]
Sorry @nishnik I haven't seen the semantics of ProbeModelXML, so I cannot comment. This link might help you http://leo.ugr.es/pgm2012/submissions/pgm2012_submission_43.pdf

**Comment by satrana42** [comment]
@khalibartan What exactly needs to be done in 'models/MarkovModel.py: # TODO : Convert factor into CPDs' ? I have some understanding of PGMs and I'm looking for a first patch.

**Comment by khalibartan** [comment]
@satwantrana As per my knowledge someone was working on it. Check if there is a patch for it or not. Otherwise, this issue is about having a method to convert our factor representation to our `TabularCPD` representation , I recommend that you discuss it with @ankurankan over the thread #595 , there is some work to be done in `TabularCPD class`, if there is some API change decision taken then you have to wait otherwise, it is fairly easy.

You can look for both classes at here https://github.com/pgmpy/pgmpy/tree/dev/pgmpy/factors

**Comment by aelnouby** [comment]
@khalibartan  What are the bugs exactly in this ?

> models/DynamicBayesianNetwork.py: # TODO: fix bugs in this

**Comment by khalibartan** [comment]
I don't know myself.

**Comment by lohani2280** [comment]
@ankurankan Regarding :: `models/DynamicBayesianNetwork.py: # TODO: fix bugs in this` . 
I think in the implementation of `get_cpds`  method of DBN we should add `initialize_initial_state` method in the beginning. This way the user can get cpds of those nodes with time_slice other than 0. 
Although this way we would be stuck in an infinite loop. But still i thought some discussions over this would let us to a proper solution.  

Right now if the user calls `get_cpds` method after adding cpds to the DBN then it displays only the cpds of those nodes with time_slice = 0 . 

I think this is the bug in `get_cpds` method of DBN. Please correct me if i am wrong here.

**Comment by ankurankan** [comment]
@lohani2280 I am not sure if that would be a great idea. While implementing DBNs we had decided to keep the representation as short as possible and that's why we had decided to represent it using one and a half model and in my opinion that much information should be enough for anyone to understand the structure of the model. Even if we implement returning `get_cpds` for different time slices we would just be showing the same values with a different value for time which should in my opinion should be obvious to the user. So, I don't think this feature would be worth spending time on.

**Comment by lohani2280** [comment]
@ankurankan Yes, i agree with you. But  can you please point me out what exactly is the bug in this method as its tagged with a `TODO` label.

**Comment by ankurankan** [comment]
@lohani2280 I don't really know :D. And I don't think anyone knows (as @khalibartan has also mentioned in a previous comment). But my best guess would be https://github.com/pgmpy/pgmpy/issues/664. 

And that's why we need to write better messages everywhere explaining things. This one is on me:
```
$ git blame pgmpy/models/DynamicBayesianNetwork.py -L 401,401
23dc031f (Ankur Ankan 2015-08-29 08:25:34 +0530 401)         # TODO: fix bugs in this
```

**Comment by lohani2280** [comment]
@ankurankan  Okay, will try to look into it :+1:
